data:
  dataset_path: data/processed/cases_only_v1_20200301_to_20220726.zarr
model:
  type:
    cases: true
    regions: false
    biomarkers: false
    mobility: false
  params:
    biomarkers_dim: 1
    cases_dim: 1
    forecast_horizon: 7
    mobility_embedding_dim: 64
    region_embedding_dim: 64
    sequence_length: 14
    ego_graph_params:
      history_length: 14
      min_flow_threshold: 10
      max_neighbors: 20
output:
  experiment_name: epiforecaster_base_experiment
  log_dir: outputs/training
training:
  device: "cpu"
  batch_size: 4
  early_stopping_patience: 5
  epochs: 1
  learning_rate: 0.001
  weight_decay: 1.0e-05
  num_workers: 0
  validation_split: 0.01 # Use only 1% for validation to reduce processing time
